In [1]:
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
df=load_digits()
print(dir(df))

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']


In [2]:
x=df.data
y=df.target

In [3]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [4]:
model=LogisticRegression(solver="lbfgs",max_iter=3000)
model.fit(X_train,Y_train)
print(model.score(X_test,Y_test)*100)

96.94444444444444


In [6]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits
df=load_digits()
print(dir(df))

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']


In [7]:
x=df.data
y=df.target

In [8]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [10]:
model=SVC()
model.fit(X_train,Y_train)
print(model.score(X_test,Y_test)*100)

99.16666666666667


In [11]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits
df=load_digits()
print(dir(df))

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']


In [12]:
x=df.data
y=df.target

In [18]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [19]:
model=RandomForestClassifier(n_estimators=40)
model.fit(X_train,Y_train)
print(model.score(X_test,Y_test)*100)

97.22222222222221


In [26]:
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_digits
import numpy as np
df=load_digits()
x=df.data
y=df.target


In [27]:
model1=LogisticRegression(solver="lbfgs",max_iter=3000)
model2=SVC()
model3=RandomForestClassifier()
score1=cross_val_score(model1,x,y,cv=3)
score2=cross_val_score(model2,x,y,cv=3)
score3=cross_val_score(model3,x,y,cv=3)
score1

array([0.91986644, 0.94156928, 0.91652755])

In [28]:
score2

array([0.96494157, 0.97996661, 0.96494157])

In [29]:
score3

array([0.93989983, 0.94991653, 0.92153589])

In [30]:
print(np.average(score1))
print(np.average(score2))
print(np.average(score3))

0.9259877573734001
0.9699499165275459
0.9371174179187535


In [32]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_digits
df=load_digits()
x=df.data
y=df.target

In [35]:
model1=LogisticRegression(solver="lbfgs",max_iter=3000)
model2=SVC()
model3=RandomForestClassifier()
score1=cross_val_score(model1,x,y,cv=3)
score2=cross_val_score(model2,x,y,cv=3)
score3=cross_val_score(model3,x,y,cv=3)
score1


array([0.91986644, 0.94156928, 0.91652755])

In [36]:
score2

array([0.96494157, 0.97996661, 0.96494157])

In [37]:
score3

array([0.93989983, 0.94824708, 0.92654424])

In [39]:
print(np.average(score1)*100)
print(np.average(score2)*100)
print(np.average(score3)*100)

92.59877573734
96.99499165275459
93.82303839732887


In [40]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_digits
df=load_digits()
x=df.data
y=df.target

In [42]:
model1=LogisticRegression(solver="lbfgs",max_iter=3000)
model2=RandomForestClassifier(n_estimators=40)
model3=SVC()
score1=cross_val_score(model1,x,y,cv=5)
score2=cross_val_score(model2,x,y,cv=5)
score3=cross_val_score(model3,x,y,cv=5)
score1


array([0.92222222, 0.86944444, 0.94150418, 0.94150418, 0.89693593])

In [43]:
score2

array([0.91666667, 0.92777778, 0.94707521, 0.96100279, 0.91643454])

In [44]:
score3

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [45]:
print(np.average(score1))
print(np.average(score2))
print(np.average(score3))

0.914322191272052
0.9337913958526773
0.9632838130609718
